---
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: inbound-frontend
spec:
  sources:
    - match:
        kuma.io/service: 'kong-UPDATE_ME-kong-proxy_kong_svc_80'
  destinations:
    - match:
        kuma.io/service: 'frontend_kuma-demo_svc_8080'
